<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 1997, 2020 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Distribution License v. 1.0, which is available at
    http://www.eclipse.org/org/documents/edl-v10.php.

    SPDX-License-Identifier: BSD-3-Clause

-->

<descriptor since="2.0">
    <description>This is a fromwsdl SOAP 1.2 fault test</description>
    <service basedir="./server">
        <wsdl href="fault.wsdl"/>
    </service>
    <client name="fault1">
        <description>
            Test WSDL Fault1.
        </description>
            try {
                faultPort.echo("Fault1");
                fail("no exception was received");
            } catch (Fault1Exception e) {
                System.out.println("Expected exception received: " + e.getMessage());
            }
    </client>

    <client name="fault2">
        <description>
            Test WSDL fault2
        </description>
            try {
                faultPort.echo("Fault2");
                fail("no exception was received");
            } catch (Fault2Exception e) {
                System.out.println("Expected exception received: " + e.getMessage());
            }
    </client>

    <client name="fault3">
        <description>
            Test WSDL fault3
        </description>
            try {
                faultPort.echo("Fault3");
                fail("no exception was received");
            } catch (Fault3Exception e) {
                System.out.println("Expected exception received: " + e.getMessage());
            }
    </client>

    <client name="fault4">
        <description>
            Test WSDL fault4
        </description>
            try {
                faultPort.echo("Fault4");
                fail("no exception was received");
            } catch (Fault4Exception e) {
                System.out.println("Expected exception received: " + e.getMessage());
            }
    </client>
    <client name="npe">
        <description>
            Test NullPointerException
        </description>
            try {
                faultPort.echo("NullPointerException");
                fail("no exception was received");
            } catch (jakarta.xml.ws.ProtocolException e) {
                System.out.println("Expected exception received: " + e.getMessage());
            }
    </client>

    <client name="testSOAP12FaultException">
        <description>
            Tests SOAP 1.2 SOAPFaultException
        </description>
            try {
                faultPort.echo("SOAPFaultException");
                fail("no exception was received");
            } catch (jakarta.xml.ws.ProtocolException e) {
                if (e instanceof SOAPFaultException) {
                    System.out.println("Expected exception received: " + e.getMessage());
                    SOAPFaultException sfe = (SOAPFaultException)e;
                    assertNotNull(sfe.getFault().getDetail());
                } else {
                    fail("received incorrect exception: " + e);
                }
            }
    </client>

    <client name="fault1WithCause">
        <description>
            Tests WSDL faul1 with cause
        </description>
            try {
                String ret = faultPort.echo("Fault1-SOAPFaultException");
                fail("no exception was received");
            } catch (Fault1Exception e) {
                System.out.println("Expected exception received: " + e.getMessage());
            }
    </client>

    <client name="testProtocolException">
        <description>
            Test ProtocolException()
        </description>
            try {
                faultPort.echo("ProtocolException");
                fail("no exception was received");
            } catch (jakarta.xml.ws.ProtocolException e) {
                // pass if ProtocolException received
            }
    </client>

    <client name="testProtocolExceptionWithMessage">
        <description>
            Test ProtocolException with message
        </description>
        try {
            faultPort.echo("ProtocolException2");
            fail("no exception was received");
        } catch (jakarta.xml.ws.ProtocolException e) {
            assertNotNull("message in exception is null", e.getMessage());
            System.out.println("Expected exception received: " + e.getMessage());
            if (e.getMessage().indexOf("FaultImpl") == -1) {
                fail();
            }
        }
    </client>
</descriptor>
